In [3]:
import numpy as np
data = np.sin(np.arange(20)).reshape(5,4)
print (data)
ind = data.argmax(axis=0)#按列 返回数值最大数的下标
print (ind)
data_max = data[ind, range(data.shape[1])]
print (data_max)
print(data.max(axis=0))
all(data_max == data.max(axis=0))#all()  any()

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[ 0.98935825  0.84147098  0.99060736  0.6569866 ]
[ 0.98935825  0.84147098  0.99060736  0.6569866 ]


True

In [10]:
a = np.arange(0, 40, 10)
print (a)
print ('---')
b = np.tile(a, (2, 4))#numpy.tile(A,reps) tile共有2个参数，A指待输入数组，reps则决定A重复的次数
c = np.tile(a,3)

print (b)
print (c)

[ 0 10 20 30]
---
[[ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]]
[ 0 10 20 30  0 10 20 30  0 10 20 30]


In [12]:
a = np.array([[4, 3, 5], [1, 2, 1]])
print (a)
b = np.sort(a, axis=1)
print (b)
a.sort(axis=1)
print (a)
a = np.array([4, 3, 1, 2])
j = np.argsort(a)#返回的是数组值从小到大的索引值
print (j)
print (a[j])

[[4 3 5]
 [1 2 1]]
[[3 4 5]
 [1 1 2]]
[[3 4 5]
 [1 1 2]]
[2 3 1 0]
[1 2 3 4]
