In [2]:
import numpy as np
B = np.arange(3)
print (B)
#print (np.exp(B))
print (np.sqrt(B))

[0 1 2]
[0.         1.         1.41421356]


In [18]:
#返回不大于输入参数的最大整数
a = np.floor(10*np.random.random((3,4)))
print (a)

# print(a.shape)
# # 将多维数组降位一维，行序优先
# print (a.ravel())
# print(a.ravel('F'))#列序优先
##同a.ravel()将多维数组降位一维,两者的区别在于flatten返回拷贝（copy）ravel返回视图（view）
#print(a.flatten())
# a.shape = (6, 2)
# print (a) 
# print (a.T)#a.T表示a的转置
# print (a.resize((2,6)))
# print (a)

#reshape函数当参数只有一个-1时表示将数组降为一维
#如果整形操作中给定的维度为-1，则自动计算其他维度
print(a.reshape(3,-1))
print(a.reshape(-1))
print(a.T.reshape(-1))

[[ 0.  7.  7.  3.]
 [ 5.  0.  7.  8.]
 [ 4.  9.  8.  9.]]
[ 0.  7.  7.  3.  5.  0.  7.  8.  4.  9.  8.  9.]
[[ 0.  7.  7.  3.]
 [ 5.  0.  7.  8.]
 [ 4.  9.  8.  9.]]
[ 0.  7.  7.  3.  5.  0.  7.  8.  4.  9.  8.  9.]
[ 0.  5.  4.  7.  0.  9.  7.  7.  8.  3.  8.  9.]


In [20]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print (a)
print ('---')
print (b)
print ('---')
print(np.vstack((a,b)))#沿着竖直方向将矩阵堆叠起来
print(np.hstack((a,b)))#沿着水平方向将数组堆叠起来

[[ 6.  4.]
 [ 3.  8.]]
---
[[ 3.  3.]
 [ 0.  6.]]
---
[[ 6.  4.]
 [ 3.  8.]
 [ 3.  3.]
 [ 0.  6.]]
[[ 6.  4.  3.  3.]
 [ 3.  8.  0.  6.]]


In [28]:
a = np.floor(10*np.random.random((2,12)))
print (a)
print (np.hsplit(a,3))  #水平方向切成3个
print (np.hsplit(a,(3,4)))   #水平方向下标为3处切以下，4处切一下
a = np.floor(10*np.random.random((12,2)))
print (a)
print(np.vsplit(a,3))  #竖直方向切成3个

[[ 7.  6.  4.  5.  3.  6.  8.  4.  5.  0.  0.  8.]
 [ 4.  0.  1.  8.  3.  9.  4.  9.  7.  3.  3.  9.]]
[array([[ 7.,  6.,  4.,  5.],
       [ 4.,  0.,  1.,  8.]]), array([[ 3.,  6.,  8.,  4.],
       [ 3.,  9.,  4.,  9.]]), array([[ 5.,  0.,  0.,  8.],
       [ 7.,  3.,  3.,  9.]])]
[array([[ 7.,  6.,  4.],
       [ 4.,  0.,  1.]]), array([[ 5.],
       [ 8.]]), array([[ 3.,  6.,  8.,  4.,  5.,  0.,  0.,  8.],
       [ 3.,  9.,  4.,  9.,  7.,  3.,  3.,  9.]])]
[[ 2.  4.]
 [ 3.  9.]
 [ 9.  5.]
 [ 1.  6.]
 [ 6.  0.]
 [ 1.  0.]
 [ 8.  6.]
 [ 5.  9.]
 [ 8.  3.]
 [ 5.  7.]
 [ 8.  2.]
 [ 1.  6.]]
[array([[ 2.,  4.],
       [ 3.,  9.],
       [ 9.,  5.],
       [ 1.,  6.]]), array([[ 6.,  0.],
       [ 1.,  0.],
       [ 8.,  6.],
       [ 5.,  9.]]), array([[ 8.,  3.],
       [ 5.,  7.],
       [ 8.,  2.],
       [ 1.,  6.]])]


In [46]:
#简单的赋值不会复制数组对象或其数据。
a = np.arange(12)
b = a
b is a
b.shape = 3,4
print (a.shape)
print (id(a))#id类似于c++的取地址&。
print (id(b))

#视图方法创建一个新的数组对象，该数组对象查看相同的数据。
c = a.view()
c is a
c.shape = 2,6
print (a.shape)
c[0,4] = 1234
print(a)
print(id(a))
print(id(c))
print(a.flags.owndata)#数据由 a 保管
print(c.flags.owndata)#c并不保管数据

(3, 4)
1501079060688
1501079060688
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
1501079060688
1501079061728
True
False


In [47]:
#复制方法对数组及其数据进行完整的复制。
d = a.copy() 
d[0,0] = 9999
d.shape=2,6
print (d) 
print (a)
print(id(d))
print(id(a))
print(a.flags.owndata)
print(d.flags.owndata)

[[9999    1    2    3 1234    5]
 [   6    7    8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
1501079060608
1501079060688
True
True
