In [9]:
import numpy

world_alcohol = numpy.genfromtxt("world_alcohol.txt", delimiter=",")
print(type(world_alcohol))

<type 'numpy.ndarray'>


In [3]:
#array()函数可以接受一个或多个list作为输入。当我们输入一个列表，我们得到一个一维数组的结果:
vector = numpy.array([5, 10, 15, 20])
#当我们输入几个list，我们得到一个矩阵的结果:
matrix = numpy.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print vector
print matrix

[ 5 10 15 20]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [4]:
#我们可以用ndarray.shape属性来计算数组中有多少元素
vector = numpy.array([1, 2, 3, 4])
print(vector.shape)
#对于矩阵，shape属性包含一个包含两个元素的元组
matrix = numpy.array([[5, 10, 15], [20, 25, 30]])
print(matrix.shape)

(4,)
(2, 3)


In [5]:
#NumPy数组中的每个值必须具有相同的数据类型
#当读取数据或将列表转换为数组时，NumPy将自动计算出适当的数据类型。
#可以使用dtype属性检查NumPy数组的数据类型。
numbers = numpy.array([1, 2, 3, 4])
numbers.dtype

dtype('int32')

In [10]:
#当NumPy无法将值转换为浮点或整数之类的数字数据类型时，它将使用一个特殊的nan值，该值表示非数字
#nan = not a number
world_alcohol

array([[             nan,              nan,              nan,
                     nan,              nan],
       [  1.98600000e+03,              nan,              nan,
                     nan,   0.00000000e+00],
       [  1.98600000e+03,              nan,              nan,
                     nan,   5.00000000e-01],
       ..., 
       [  1.98700000e+03,              nan,              nan,
                     nan,   7.50000000e-01],
       [  1.98900000e+03,              nan,              nan,
                     nan,   1.50000000e+00],
       [  1.98500000e+03,              nan,              nan,
                     nan,   3.10000000e-01]])

In [11]:
world_alcohol = numpy.genfromtxt("world_alcohol.txt", delimiter=",", dtype="U75", skip_header=1)
print(world_alcohol)

[[u'1986' u'Western Pacific' u'Viet Nam' u'Wine' u'0']
 [u'1986' u'Americas' u'Uruguay' u'Other' u'0.5']
 [u'1985' u'Africa' u"Cte d'Ivoire" u'Wine' u'1.62']
 ..., 
 [u'1987' u'Africa' u'Malawi' u'Other' u'0.75']
 [u'1989' u'Americas' u'Bahamas' u'Wine' u'1.5']
 [u'1985' u'Africa' u'Malawi' u'Spirits' u'0.31']]


In [12]:
uruguay_other_1986 = world_alcohol[1,4]
third_country = world_alcohol[2,2]
print uruguay_other_1986
print third_country

0.5
Cte d'Ivoire


In [13]:
vector = numpy.array([5, 10, 15, 20])
print(vector[0:3])  

[ 5 10 15]


In [14]:
matrix = numpy.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
print(matrix[:,1])

[10 25 40]


In [15]:
matrix = numpy.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
print(matrix[:,0:2])

[[ 5 10]
 [20 25]
 [35 40]]


In [12]:
matrix = numpy.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
print(matrix[1:3,0:2])

[[20 25]
 [35 40]]
