In [1]:
import numpy as np
#交换矩阵的其中两行
a = np.arange(25).reshape(5,5)
print (a)
a[[0,1]] = a[[1,0]]
print (a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
#找出数组中与给定值最接近的数
z = np.array([[0,1,3,2],[4,5,6,7]])
a = 3.4
print (np.abs(z-a).argmin())# 给出axis方向最小值的下标 模型axis = 1

2


In [5]:
#判断二维矩阵中有没有一整列数为0？
z = np.random.randint(0,3,(2,10))#产生离散均匀分布的整数，这些整数大于等于low，小于high。
print (z)
print (z.any(axis=0))

[[1 2 1 0 0 0 0 2 1 1]
 [2 1 1 2 0 1 2 0 0 2]]
[ True  True  True  True False  True  True  True  True  True]


In [8]:
#生成二维的高斯矩阵
x,y = np.meshgrid(np.linspace(-1,1,5),np.linspace(-1,1,5))  #linspace  指定的间隔内返回均匀间隔的数字
print (x)
print ('---')
print (y)
print ('---')
D = np.sqrt(x**2+y**2)
print (D)
print ('---')
sigma,mu = 1,0
a = np.exp(-(D-mu)**2/(2*sigma**2))
print (a)

[[-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]]
---
[[-1.  -1.  -1.  -1.  -1. ]
 [-0.5 -0.5 -0.5 -0.5 -0.5]
 [ 0.   0.   0.   0.   0. ]
 [ 0.5  0.5  0.5  0.5  0.5]
 [ 1.   1.   1.   1.   1. ]]
---
[[ 1.41421356  1.11803399  1.          1.11803399  1.41421356]
 [ 1.11803399  0.70710678  0.5         0.70710678  1.11803399]
 [ 1.          0.5         0.          0.5         1.        ]
 [ 1.11803399  0.70710678  0.5         0.70710678  1.11803399]
 [ 1.41421356  1.11803399  1.          1.11803399  1.41421356]]
---
[[ 0.36787944  0.53526143  0.60653066  0.53526143  0.36787944]
 [ 0.53526143  0.77880078  0.8824969   0.77880078  0.53526143]
 [ 0.60653066  0.8824969   1.          0.8824969   0.60653066]
 [ 0.53526143  0.77880078  0.8824969   0.77880078  0.53526143]
 [ 0.36787944  0.53526143  0.60653066  0.53526143  0.36787944]]
